services:
  diffusion-policy:
    build:
      context: .
      dockerfile: Dockerfile #if the image exist localy, it will take it directly, if no , it will build the image and take it
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: diffusion-policy
    container_name: ${CONTAINER_NAME}
    network_mode: host
    privileged: true
    restart: alwayss
    volumes:
      - .:/diffusion-policy  # Same as -v $(pwd):/diffusion-policy
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Enables GPU access
    stdin_open: true
    tty: true	

